### ISSUE TITLE
`hurley new` fails with `UnhandledPromiseRejectionWarning` because listing docker images doesn't escape bash wildcard

### ISSUE THREAD

**Issue by hbobenicio** [worldsibu/hurley#163]
hurley new results in this output:

```
===> List out hyperledger docker images
{ [String: 'Installing Hyperledger Fabric binaries\nBinaries exist already\nChecking IMAGES\n===> Pulling fabric Images\n==> FABRIC IMAGE: peer\n\n1.4.0: Pulling from hyperledger/fabric-peer\nDigest: sha256:9707c97f787de1d4d6dd60994d6b8ea2e5cc28b0f42e6849df3fb41c64b41372\nStatus: Image is up to date for hyperledger/fabric-peer:1.4.0\n==> FABRIC IMAGE: orderer\n\n1.4.0: Pulling from hyperledger/fabric-orderer\nDigest: sha256:644265186b4887c7d9dcb91895124ccead3c0125c2c4f9eadc421dc9555d7495\nStatus: Image is up to date for hyperledger/fabric-orderer:1.4.0\n==> FABRIC IMAGE: tools\n\n1.4.0: Pulling from hyperledger/fabric-tools\nDigest: sha256:aee256916d0cb938d8023fa32ed2745991d32cfe79018e360f1720707ebfbdb5\nStatus: Image is up to date for hyperledger/fabric-tools:1.4.0\n===> Pulling fabric ca Image\n==> FABRIC CA IMAGE\n\n1.4.0: Pulling from hyperledger/fabric-ca\nDigest: sha256:c1dce534d9e9202697e0aaad7c5521d958700fda0b05127dafb9333c22e15f74\nStatus: Image is up to date for hyperledger/fabric-ca:1.4.0\n===> Pulling thirdparty docker images\n==> THIRDPARTY DOCKER IMAGE: couchdb\n\n0.4.14: Pulling from hyperledger/fabric-couchdb\nDigest: sha256:021c7e4a5047432d892fbdf7d5220d3049ff4e8b436fd481bb08e41871f1aac7\nStatus: Image is up to date for hyperledger/fabric-couchdb:0.4.14\n\n===> List out hyperledger docker images\n']
  stdout:
   'Installing Hyperledger Fabric binaries\nBinaries exist already\nChecking IMAGES\n===> Pulling fabric Images\n==> FABRIC IMAGE: peer\n\n1.4.0: Pulling from hyperledger/fabric-peer\nDigest: sha256:9707c97f787de1d4d6dd60994d6b8ea2e5cc28b0f42e6849df3fb41c64b41372\nStatus: Image is up to date for hyperledger/fabric-peer:1.4.0\n==> FABRIC IMAGE: orderer\n\n1.4.0: Pulling from hyperledger/fabric-orderer\nDigest: sha256:644265186b4887c7d9dcb91895124ccead3c0125c2c4f9eadc421dc9555d7495\nStatus: Image is up to date for hyperledger/fabric-orderer:1.4.0\n==> FABRIC IMAGE: tools\n\n1.4.0: Pulling from hyperledger/fabric-tools\nDigest: sha256:aee256916d0cb938d8023fa32ed2745991d32cfe79018e360f1720707ebfbdb5\nStatus: Image is up to date for hyperledger/fabric-tools:1.4.0\n===> Pulling fabric ca Image\n==> FABRIC CA IMAGE\n\n1.4.0: Pulling from hyperledger/fabric-ca\nDigest: sha256:c1dce534d9e9202697e0aaad7c5521d958700fda0b05127dafb9333c22e15f74\nStatus: Image is up to date for hyperledger/fabric-ca:1.4.0\n===> Pulling thirdparty docker images\n==> THIRDPARTY DOCKER IMAGE: couchdb\n\n0.4.14: Pulling from hyperledger/fabric-couchdb\nDigest: sha256:021c7e4a5047432d892fbdf7d5220d3049ff4e8b436fd481bb08e41871f1aac7\nStatus: Image is up to date for hyperledger/fabric-couchdb:0.4.14\n\n===> List out hyperledger docker images\n',
  stderr: '',
  code: 1,
  cat: [Function: bound ],
  exec: [Function: bound ],
  grep: [Function: bound ],
  head: [Function: bound ],
  sed: [Function: bound ],
  sort: [Function: bound ],
  tail: [Function: bound ],
  to: [Function: bound ],
  toEnd: [Function: bound ],
  uniq: [Function: bound ] }
[hurley] - Found error while running script!
(node:17553) UnhandledPromiseRejectionWarning: Error: Errors found in script, stopping execution
    at Object.<anonymous> (/myapp/node_modules/@worldsibu/hurley/dist/utils/sysWrapper.js:119:27)
    at step (/myapp/node_modules/tslib/tslib.js:136:27)
    at Object.next (/myapp/node_modules/tslib/tslib.js:117:57)
    at /myapp/node_modules/tslib/tslib.js:110:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/myapp/node_modules/tslib/tslib.js:106:16)
    at Object.execContent (/myapp/node_modules/@worldsibu/hurley/dist/utils/sysWrapper.js:112:24)
    at DownloadFabricBinariesGenerator.BaseGenerator.run (/myapp/node_modules/@worldsibu/hurley/dist/generators/base.js:18:40)
    at NetworkCLI.<anonymous> (/myapp/node_modules/@worldsibu/hurley/dist/cli.js:191:53)
    at step (/myapp/node_modules/tslib/tslib.js:136:27)
(node:17553) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:17553) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code
```

**Comment by hbobenicio** [comment]
fixed by #164 .
released by [v1.1.4](https://github.com/worldsibu/hurley/pull/166)
