### ISSUE TITLE
Integrate with Hyperledger Caliper

### ISSUE THREAD

**Issue by levanthanh3005** [worldsibu/hurley#204]
Hello,
After building smart contract, I would like to test benmark with the contract with Hyperledger Caliper.
I attached the fabric.yaml here,
[fabric.yaml.zip](https://github.com/worldsibu/hurley/files/4511754/fabric.yaml.zip)
After running, An error happens:

Error: Fabric 1.0 compatibility mode is detected, but SDK version 1.4.0 is used
    at new Fabric (/hyperledger/caliper/node_modules/@hyperledger/caliper-fabric/lib/fabric.js:198:19)
    at Function.handler (/hyperledger/caliper/node_modules/@hyperledger/caliper-cli/lib/benchmark/lib/runBenchmark.js:61:33)
    at Object.module.exports.handler (/hyperledger/caliper/node_modules/@hyperledger/caliper-cli/lib/benchmark/runBenchmarkCommand.js:52:43)
    at Object.runCommand (/hyperledger/caliper/node_modules/yargs/lib/command.js:228:22)
    at Object.parseArgs [as _parseArgs] (/hyperledger/caliper/node_modules/yargs/yargs.js:1013:30)
    at Object.runCommand (/hyperledger/caliper/node_modules/yargs/lib/command.js:194:45)
    at Object.parseArgs [as _parseArgs] (/hyperledger/caliper/node_modules/yargs/yargs.js:1013:30)
    at Object.get [as argv] (/hyperledger/caliper/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/hyperledger/caliper/node_modules/@hyperledger/caliper-cli/caliper.js:35:5)
    at Module._compile (module.js:635:30)

Could you please see if I made any mistake

**Comment by levanthanh3005** [comment]
@diestrin Could you please take a look

**Comment by diestrin** [comment]
Well, from the error it seem like it needs Fabric 1.0 but Hurley uses Fabric 1.4

**Comment by levanthanh3005** [comment]
Hi,
The config is similar with 
https://github.com/hyperledger/caliper-benchmarks/blob/master/networks/fabric/fabric-v1.4.0/2org1peercouchdb/fabric-node.yaml
But I dont know why it fails
