### ISSUE TITLE
chaincode invoke error

### ISSUE THREAD

**Issue by jackyjqcheung** [worldsibu/hurley#69]
when i try to invoke the chaincode by hurley, it throws an error.  The chaincode has been installed and instantiated successfully. Any idea?

> fabcar@0.1.0 cc:install /home/osboxes/fabric/convector/fabcar
> f() { hurl install ${2:-$1} node -P ./chaincode-$1; }; f "car" "org1"

[hurley] - installing smart contract located at /home/osboxes/fabric/convector/fabcar/chaincode-car
Installing Chaincode org1 version 1.0 at org1
2019-08-30 17:45:51.396 EDT [chaincodeCmd] checkChaincodeCmdParams -> INFO 001 Using default escc
2019-08-30 17:45:51.396 EDT [chaincodeCmd] checkChaincodeCmdParams -> INFO 002 Using default vscc
2019-08-30 17:45:51.433 EDT [chaincodeCmd] install -> INFO 003 Installed remotely response:<status:200 payload:"OK" > 
Installed Chaincode org1 version 1.0 at org1
Installing Chaincode org1 version 1.0 at org2
2019-08-30 17:45:51.515 EDT [chaincodeCmd] checkChaincodeCmdParams -> INFO 001 Using default escc
2019-08-30 17:45:51.516 EDT [chaincodeCmd] checkChaincodeCmdParams -> INFO 002 Using default vscc
2019-08-30 17:45:51.545 EDT [chaincodeCmd] install -> INFO 003 Installed remotely response:<status:200 payload:"OK" > 
Installed Chaincode org1 version 1.0 at org2
Instantiating Chaincode at org1 for channel ch1
It may take a few minutes depending on the chaincode dependencies
2019-08-30 17:46:01.617 EDT [chaincodeCmd] checkChaincodeCmdParams -> INFO 001 Using default escc
2019-08-30 17:46:01.617 EDT [chaincodeCmd] checkChaincodeCmdParams -> INFO 002 Using default vscc
Instantiated Chaincode at org1

~/fabric/convector/fabcar$ hurl invoke car car_create '{"model": "Prius", "colour": "blue", "owner": "Tomoko"}'
[hurley] - {"model": "Prius", "colour": "blue", "owner": "Tomoko"}
(node:9466) UnhandledPromiseRejectionWarning: TypeError: network.organizations.find is not a function
    at ChaincodeCLI.<anonymous> (/home/osboxes/.nvm/versions/node/v8.11.4/lib/node_modules/@worldsibu/hurley/dist/cli.js:428:53)
    at step (/home/osboxes/.nvm/versions/node/v8.11.4/lib/node_modules/@worldsibu/hurley/node_modules/tslib/tslib.js:136:27)
    at Object.next (/home/osboxes/.nvm/versions/node/v8.11.4/lib/node_modules/@worldsibu/hurley/node_modules/tslib/tslib.js:117:57)
    at fulfilled (/home/osboxes/.nvm/versions/node/v8.11.4/lib/node_modules/@worldsibu/hurley/node_modules/tslib/tslib.js:107:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
(node:9466) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9466) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

hurl invoke car create '{"model": "Prius", "colour": "blue", "owner": "Tomoko"}'
[hurley] - {"model": "Prius", "colour": "blue", "owner": "Tomoko"}
(node:9482) UnhandledPromiseRejectionWarning: TypeError: network.organizations.find is not a function
    at ChaincodeCLI.<anonymous> (/home/osboxes/.nvm/versions/node/v8.11.4/lib/node_modules/@worldsibu/hurley/dist/cli.js:428:53)
    at step (/home/osboxes/.nvm/versions/node/v8.11.4/lib/node_modules/@worldsibu/hurley/node_modules/tslib/tslib.js:136:27)
    at Object.next (/home/osboxes/.nvm/versions/node/v8.11.4/lib/node_modules/@worldsibu/hurley/node_modules/tslib/tslib.js:117:57)
    at fulfilled (/home/osboxes/.nvm/versions/node/v8.11.4/lib/node_modules/@worldsibu/hurley/node_modules/tslib/tslib.js:107:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
(node:9482) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9482) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Here is the enviroment info. 
~/fabric/convector/fabcar$ hurl --version
1.1.0
~/fabric/convector/fabcar$ conv --version
1.1.6
~/fabric/convector/fabcar$ node --version
v8.11.4

**Comment by diestrin** [comment]
Did you manually update your scripts or this was generated by the CLI?
`f() { hurl install ${2:-$1} node -P ./chaincode-$1; }; f "car" "org1"` wondering why this functions is getting that second argument `org1`, it doesn't need it. The second argument is to override the chaincode installation name, so your contract is being installed with the name `org1` instead of `car`, that's why the invoke fails.

**Comment by jackyjqcheung** [comment]
so I remove the project folder and do it again

 conv new car
 cd car
 npm i

npm run env:restart

the fabric started successfully then I invoke the chaincode but still got errors 

osboxes@osboxes:~/fabric/convector/car$ npm run cc:start -- car

> car@0.1.0 cc:start /home/osboxes/fabric/convector/car
> f() { npm run cc:package -- $1; npm run cc:install $1 $2; }; f "car"


> car@0.1.0 cc:package /home/osboxes/fabric/convector/car
> f() { npm run lerna:build; chaincode-manager --update --config ./$1.config.json --output ./chaincode-$1 package; }; f "car"


> car@0.1.0 lerna:build /home/osboxes/fabric/convector/car
> lerna run build

lerna notice cli v3.13.4
lerna info Executing command in 1 package: "npm run build"
lerna info run Ran npm script 'build' in 'car-cc' in 2.9s:

> car-cc@0.1.0 build /home/osboxes/fabric/convector/car/packages/car-cc
> npm run clean && tsc


> car-cc@0.1.0 clean /home/osboxes/fabric/convector/car/packages/car-cc
> rimraf dist client

lerna success run Ran npm script 'build' in 1 package in 2.9s:
lerna success - car-cc

> car@0.1.0 cc:install /home/osboxes/fabric/convector/car
> f() { hurl install ${2:-$1} node -P ./chaincode-$1; }; f "car"

[hurley] - installing smart contract located at /home/osboxes/fabric/convector/car/chaincode-car
Installing Chaincode car version 1.0 at org1
2019-08-30 19:23:47.469 EDT [chaincodeCmd] checkChaincodeCmdParams -> INFO 001 Using default escc
2019-08-30 19:23:47.470 EDT [chaincodeCmd] checkChaincodeCmdParams -> INFO 002 Using default vscc
2019-08-30 19:23:47.510 EDT [chaincodeCmd] install -> INFO 003 Installed remotely response:<status:200 payload:"OK" > 
Installed Chaincode car version 1.0 at org1
Installing Chaincode car version 1.0 at org2
2019-08-30 19:23:47.594 EDT [chaincodeCmd] checkChaincodeCmdParams -> INFO 001 Using default escc
2019-08-30 19:23:47.594 EDT [chaincodeCmd] checkChaincodeCmdParams -> INFO 002 Using default vscc
2019-08-30 19:23:47.623 EDT [chaincodeCmd] install -> INFO 003 Installed remotely response:<status:200 payload:"OK" > 
Installed Chaincode car version 1.0 at org2
Instantiating Chaincode at org1 for channel ch1
It may take a few minutes depending on the chaincode dependencies
2019-08-30 19:23:57.692 EDT [chaincodeCmd] checkChaincodeCmdParams -> INFO 001 Using default escc
2019-08-30 19:23:57.692 EDT [chaincodeCmd] checkChaincodeCmdParams -> INFO 002 Using default vscc
Instantiated Chaincode at org1


osboxes@osboxes:~/fabric/convector/car$ hurl invoke car car_create '{"name": "jetta", "created": 1, "modified": 1}'
[hurley] - {"name": "jetta", "created": 1, "modified": 1}
(node:1376) UnhandledPromiseRejectionWarning: TypeError: network.organizations.find is not a function
    at ChaincodeCLI.<anonymous> (/home/osboxes/.nvm/versions/node/v8.11.4/lib/node_modules/@worldsibu/hurley/dist/cli.js:428:53)
    at step (/home/osboxes/.nvm/versions/node/v8.11.4/lib/node_modules/@worldsibu/hurley/node_modules/tslib/tslib.js:136:27)
    at Object.next (/home/osboxes/.nvm/versions/node/v8.11.4/lib/node_modules/@worldsibu/hurley/node_modules/tslib/tslib.js:117:57)
    at fulfilled (/home/osboxes/.nvm/versions/node/v8.11.4/lib/node_modules/@worldsibu/hurley/node_modules/tslib/tslib.js:107:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
(node:1376) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1376) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


   ╭──────────────────────────────────────────────╮
   │                                              │
   │       Update available 1.0.6 → 1.1.0         │
   │   Run npm i -g @worldsibu/hurley to update   │
   │                                              │
   ╰──────────────────────────────────────────────╯

**Comment by diestrin** [comment]
Hey @jackyjqcheung I found 2 problems. First the cli was generating the project with a dependency of Hurley 1.0.6, I just pushed a new version of the CLI using Hurley 1.1.1. Second, I found a problem with the defaults in Hurley, so I just pushed version 1.1.1 of it.

Can you please update you local package.json with Hurley 1.1.1, run `npm i` and try again? Thanks

**Comment by jackyjqcheung** [comment]
The new version 1.1.1 works.  Thanks.
