### ISSUE TITLE
Unable to install in Ubuntu x509 error

### ISSUE THREAD

**Issue by michaelspeed** [worldsibu/hurley#99]
**installations** - (all are done with **root access**)
```
npm install node-gyp -g --unsafe-perm
npm i -g @worldsibu/hurley --unsafe-perm=true --allow-root
```

environment - 
```
Ubuntu 16.04 LTS (GNU/Linux 4.4.0-21-generic x86_64)
node - 8.9.0 / 8.11.0 / 11.10.0
```

**error** - 
```
> @ampretia/x509@0.4.0 install /usr/lib/node_modules/@worldsibu/hurley/node_modules/@ampretia/x509
> node-gyp rebuild

make: Entering directory '/usr/lib/node_modules/@worldsibu/hurley/node_modules/@ampretia/x509/build'
  CXX(target) Release/obj.target/x509/src/addon.o
make: g++: Command not found
x509.target.mk:106: recipe for target 'Release/obj.target/x509/src/addon.o' failed
make: *** [Release/obj.target/x509/src/addon.o] Error 127
make: Leaving directory '/usr/lib/node_modules/@worldsibu/hurley/node_modules/@ampretia/x509/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:193:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:255:12)
gyp ERR! System Linux 4.4.0-21-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/@worldsibu/hurley/node_modules/@ampretia/x509
gyp ERR! node -v v11.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ampretia/x509@0.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
```

`environment` - 
```
Mac OS  Mojave 10.4.4
node - 8.9.0
```

`error` - 
```
> @ampretia/x509@0.4.0 install /Users/michaelspeed/.nvm/versions/node/v10.0.0/lib/node_modules/@worldsibu/hurley/node_modules/@ampretia/x509
> node-gyp rebuild

  CXX(target) Release/obj.target/x509/src/addon.o
In file included from ../src/addon.cc:5:
In file included from ../include/x509.h:6:
../../../nan/nan.h:1081:96: error: too many arguments to function call, expected at most 4, have 5
        length_ = string->WriteUtf8(v8::Isolate::GetCurrent(), str_, static_cast<int>(len), 0, flags);
                  ~~~~~~~~~~~~~~~~~                                                            ^~~~~
/Users/michaelspeed/.node-gyp/10.0.0/include/node/v8.h:2592:3: note: 'WriteUtf8' declared here
  int WriteUtf8(char* buffer,
  ^
```

**Anyone has any ideas?**

**Comment by michaelspeed** [comment]
**Solution Ubuntu**
applying build-essentials solves this issue in Ubuntu
